name: job_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # DI
  get_it: ^9.2.1
  injectable: ^2.7.1

  # Networking
  dio: ^5.10.0
  retrofit: ^4.7.3
  json_annotation: ^4.11.0

  # Layout & responsive UI
  flutter_screenutil: ^5.9.3
  logger: ^2.7.0
  custom_cached_image: ^1.7.0
  sqlite3: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.15.1
  json_serializable: ^6.13.0
  injectable_generator: ^2.7.0
  retrofit_generator: ^10.2.7

flutter:
  uses-material-design: true